name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}       
          username: ${{ secrets.EC2_USER }}     
          key: ${{ secrets.EC2_SSH_KEY }}       
          script: |
            # Update packages and install dependencies if needed
            sudo apt-get update -y
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

            # (Optional) Check/install Docker if necessary (this can be skipped if Docker is pre-installed)
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update -y
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            fi

            # Ensure the EC2 user is in the Docker group (may require a restart to take effect)
            sudo usermod -aG docker ${{ secrets.EC2_USER }}

            # Navigate to your project directory (update the path if different)
            cd /home/ubuntu/HNG12-Stage2-FastAPI-Ci-Cd

            # Synchronize the repository with the remote main branch
            git fetch --all
            git reset --hard origin/main

            # Stop and rebuild your Docker containers using docker-compose
            docker compose down
            docker compose up -d --build

            # (Optional) Restart Nginx if it's used as a reverse proxy
            # sudo systemctl restart nginx
